import {AUTHOR,signatureSvg} from '../credits/credits.js';
import {ethernetSvg} from '../wiring/ethernet.js';
import {KIT,sockets,controls,obstacles,defaultStates,calibratedKit} from '../kit/kit-definition.js';
import {experiments} from '../experiments/experiments.js';
import {routeWire} from '../routing/router.js';
import {defs,wireSvg,controlSvg,tableSvg,escapeHtml} from '../wiring/render.js';
import {simulate,validate} from '../simulation/engine.js';
import {clone,loadRecovery,persist,saveNamed,listProjects,validateImport,download} from '../storage/projects.js';
import {exportDiagram} from '../export/exporter.js';
const E=escapeHtml,$=s=>document.querySelector(s),palette=['#ec2435','#0088ed','#08b958','#f5c82c','#ef8f24','#202932','#ffffff'];
const brand='<svg viewBox="0 0 40 40" aria-hidden="true"><path fill="#ffcf49" d="m2 20 9-9 9 9-9 9z"/><path fill="#eff3f6" d="m14 9 9-9 9 9-9 9z"/><path fill="#788896" d="m14 31 9-9 9 9-9 9z"/><path fill="#eff3f6" d="m26 20 7-7 7 7-7 7z"/></svg>';
let calibration={};try{calibration=JSON.parse(localStorage.getItem('sabronpro:calibration'))||{}}catch{}
function blank(exp=experiments[0]){return {version:1,kitId:KIT.id,projectId:crypto.randomUUID(),title:exp.title,description:exp.description,experiment:exp.id,states:defaultStates(),wires:[],ethernet:null,author:{...AUTHOR},calibration:clone(calibration),table:{show:true,x:38,y:1008,width:850,fontSize:16,title:'Connection table',style:'light',columns:['Wire','From','To','Color'],useIds:false},settings:{labels:true},simulation:{}}}
let recovered=loadRecovery();try{if(recovered)validateImport(recovered,calibratedKit(recovered.calibration))}catch{recovered=null}
let project=recovered||blank(),kit=calibratedKit(project.calibration),mode='design',mapKind='sockets',selection=null,pending=null,color=palette[2],history=[],future=[],zoom=1,pan={x:0,y:0},drag=null,space=false,showZones=false,grid=false,manual=false,toastTimer,search='',pulseCount=0;
for(const c of kit.controls)if(c.type==='momentary')project.states[c.id]=0;
function resolve(id){return kit.sockets.find(s=>s.id===id)||kit.controls.find(c=>c.id===id)||kit.obstacles.find(o=>o.id===id)}
function autoroute(w,previous=project.wires.filter(v=>v.id!==w.id)){w.waypoints=routeWire(resolve(w.from),resolve(w.to),kit,previous,project.wires.indexOf(w));w.route='auto';return w;}
if(!project.wires.length&&project.experiment==='P01'){for(const w of experiments[0].wires)project.wires.push(autoroute({...w,label:w.id,notes:'',locked:false,hidden:false},project.wires));}
function commit(){history.push(clone(project));if(history.length>80)history.shift();future=[];}
function changed(full=true){project.author={...AUTHOR};kit=calibratedKit(project.calibration);const ok=persist(project);$('#saved-status').textContent=ok?'Recovered locally · autosaved':'Storage unavailable · export your project';if(full)render();else renderScene();}
function toast(text){clearTimeout(toastTimer);let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';t.setAttribute('role','status');document.body.append(t)}t.textContent=text;toastTimer=setTimeout(()=>t.remove(),3800)}
function select(type,id){selection={type,id};pending=null;render()}
function snapshotUndo(redo=false){const a=redo?future:history,b=redo?history:future;if(!a.length)return;b.push(clone(project));project=a.pop();selection=null;changed()}
function newProject(exp=experiments[3]){commit();const cal=clone(project.calibration);project=blank(exp);project.calibration=cal;kit=calibratedKit(cal);for(const w of exp.wires)project.wires.push(autoroute({...w,label:w.id,notes:'',locked:false,hidden:false},project.wires));selection=null;pending=null;changed();toast(`Loaded ${exp.title}`)}
function addWire(from,to,wireColor=color,label){if(resolve(from)?.type==='rj45_socket'||resolve(to)?.type==='rj45_socket'){toast('Use the Ethernet feature for RJ45 connections.');return false;}if(!resolve(from)||!resolve(to)||from===to){toast('Choose two different, known sockets.');return false;}commit();let n=1;while(project.wires.some(w=>w.id===`W${n}`))n++;const w=autoroute({id:`W${n}`,label:label||`W${n}`,from,to,color:wireColor,notes:'',function:'',hidden:false,locked:false});project.wires.push(w);selection={type:'wire',id:w.id};pending=null;changed();return true;}
function socketClick(id){if(mode==='design'&&resolve(id)?.type==='rj45_socket'){if(!project.ethernet)addEthernet();else select('ethernet','ETH1');return}if(mode==='map'){select('socket',id);return}if(mode!=='design')return;if(pending&&pending!==id)addWire(pending,id);else{pending=id;selection={type:'socket',id};render()}}
function setMode(m){mode=m;pending=null;drag=null;if(m==='run'){for(const c of kit.controls.filter(c=>c.type==='momentary'))project.states[c.id]=0;}render()}
function setState(id,value,record=true){if(record)commit();project.states[id]=value;changed();}
function options(selected='',onlyBanana=false){const groups=[...new Set(kit.sockets.filter(s=>s.type!=='rj45_socket'&&(!onlyBanana||s.type==='banana_socket')).map(s=>s.group))];return groups.map(g=>`<optgroup label="${E(g)}">${kit.sockets.filter(s=>s.group===g&&s.type!=='rj45_socket'&&(!onlyBanana||s.type==='banana_socket')).map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${E(s.label)} · ${s.id}</option>`).join('')}</optgroup>`).join('')}
function buttons(){return `<button data-action="new" title="New project">New</button><button data-action="open">Open</button><button data-action="save" title="Save project · Ctrl+S">Save</button><button data-action="save-as" title="Save a duplicate">Save as</button><span class="sep"></span><button data-action="undo" title="Undo · Ctrl+Z" ${history.length?'':'disabled'}>↶</button><button data-action="redo" title="Redo · Ctrl+Y" ${future.length?'':'disabled'}>↷</button><span class="sep"></span><div class="modes"><button data-mode="design" class="${mode==='design'?'active':''}">Design</button><button data-mode="run" class="${mode==='run'?'active':''}">▶ Run</button><button data-mode="map" class="${mode==='map'?'active':''}">Calibrate</button></div><span class="sep"></span><button data-action="route-all" ${mode==='run'?'disabled':''}>Auto route all</button><button data-action="export" class="primary">Export diagram</button><button data-action="manual" class="${manual?'active':''}" title="Hide editing overlays">${manual?'Exit clean view':'Clean view'}</button><div class="mobile-tabs"><button data-action="left">Tools</button><button data-action="right">Properties</button></div>`}
function init(){document.body.innerHTML=`<header><div class="brand">${brand}<div><strong>Sabron<span>Pro</span></strong><small>WIRING STUDIO</small></div></div><input class="project-title" id="project-title" aria-label="Experiment title"/><span class="saved" id="saved-status">Recovered locally · autosaved</span><button data-action="credits" class="small credit-button">♥ Credits</button><button data-action="help" class="small">Quick guide</button></header><div class="toolbar" id="toolbar"></div><main class="workspace"><aside id="left"></aside><section class="canvas-area" aria-label="Interactive kit workspace"><div class="canvas-top" id="canvas-hints"></div><svg id="canvas" xmlns="http://www.w3.org/2000/svg" aria-label="SabronPro trainer panel" role="application" tabindex="0"></svg><div class="canvas-bottom"><button data-action="zoom-out" aria-label="Zoom out">−</button><span id="zoom-label">100%</span><button data-action="zoom-in" aria-label="Zoom in">+</button><button data-action="fit">Fit</button><button data-action="one">100%</button></div></section><aside class="right" id="right"></aside></main><footer><span id="status-mode">Design</span><span id="status-selection">Click two sockets to connect</span><span class="coordinates" id="coords"></span><button class="signature" data-action="credits">Made with love <span class="heart">♥</span> by <strong>Eng. Mahmoud Shreef</strong></button><span class="end" id="warning-count"></span></footer><dialog id="modal"></dialog><input type="file" id="file-input" accept=".json,application/json" hidden/>`;bind();render();}
function render(){
 $('#project-title').value=project.title;$('#toolbar').innerHTML=buttons();$('#left').innerHTML=leftPanel();$('#right').innerHTML=rightPanel();renderScene();$('#status-mode').textContent={design:'Design mode',run:'Simulation · contacts & wiring',map:'Calibration mode'}[mode];$('#status-selection').textContent=selection?`${selection.type} · ${selection.id}`:'Click two sockets to connect';const warnings=validate(project,kit);$('#warning-count').textContent=warnings.length?`${warnings.length} wiring warning${warnings.length===1?'':'s'}`:`${kit.sockets.filter(s=>s.type==='banana_socket').length} banana sockets · ${project.wires.length} patch leads`;$('#canvas-hints').innerHTML=mode==='map'?'<span class="map">Calibration · drag a center to the physical socket</span>':mode==='run'?'<span>Hold buttons · click switches · drag knobs</span>':pending?`<span>From ${E(resolve(pending)?.label)} · choose a destination</span>`:'<span>Click two sockets to add a lead</span>';document.body.classList.toggle('manual',manual);
}
function sceneHeight(){return Math.max(1086,project.table.show?project.table.y+(project.wires.filter(w=>!w.hidden).length+(project.ethernet&&!project.ethernet.hidden?1:0)+2)*(project.table.fontSize+14):0,project.ethernet&&!project.ethernet.hidden?project.ethernet.endpoint.y+112:0)+82;}
function viewbox(){const width=1448/zoom,height=sceneHeight()/zoom;$('#canvas').setAttribute('viewBox',`${pan.x} ${pan.y} ${width} ${height}`);$('#zoom-label').textContent=`${Math.round(zoom*100)}%`}
function renderScene(){
 const sim=simulate(project,kit),svg=$('#canvas'),selected=selection?.id,searchIds=search?new Set([...kit.sockets,...kit.controls].filter(c=>(c.id+' '+c.label).toLowerCase().includes(search.toLowerCase())).map(c=>c.id)):new Set();
 let text=defs()+`<rect width="1448" height="${sceneHeight()}" fill="white" pointer-events="none"/><image id="base-panel" href="${window.PANEL_IMAGE||'panel.png'}" x="0" y="0" width="1448" height="1086"/>`;
 if(grid&&mode==='map'&&!manual)text+=`<defs><pattern id="mapgrid" width="16" height="16" patternUnits="userSpaceOnUse"><path d="M 16 0 L 0 0 0 16" stroke="#006ed4" stroke-opacity=".22" fill="none"/></pattern></defs><rect width="1448" height="1086" fill="url(#mapgrid)" pointer-events="none"/>`;
 if(showZones&&!manual)text+=kit.obstacles.map(o=>`<g data-zone="${o.id}"><rect x="${o.x}" y="${o.y}" width="${o.w}" height="${o.h}" fill="#e24c4625" stroke="#d24943" stroke-dasharray="5 5"/><text x="${o.x+4}" y="${o.y+15}" fill="#be221e" font-family="Arial" font-size="12">${E(o.label)}</text></g>`).join('');
 const drawKit=drag?.kind==='endpoint'?{...kit,sockets:kit.sockets.map(s=>{const w=project.wires.find(v=>v.id===drag.id);return s.id===w[drag.end]?{...s,x:drag.current.x,y:drag.current.y}:s})}:kit;
 text+=project.wires.map(w=>wireSvg(w,drag?.id===w.id?drawKit:kit,!manual&&w.id===selected,mode==='design'&&w.id===selected&&!manual,project.settings.labels)).join('');
 text+=kit.controls.map(c=>controlSvg(c,project.states,sim,true,mode)).join('');
 text+=ethernetSvg(project,kit,selection?.type==='ethernet'&&!manual,mode==='design'&&selection?.type==='ethernet'&&!manual,!manual,project.settings.labels);
 text+=kit.sockets.map(s=>{
 const visible=!manual&&(mode==='map'&&mapKind==='sockets'||s.id===pending||searchIds.has(s.id)||s.id===selected),isSelected=s.id===selected;
 return `<g data-socket="${s.id}" class="socket" tabindex="0" role="button" aria-label="${E(s.label)}"><title>${E(s.label)} · ${s.id} · ${project.wires.filter(w=>w.from===s.id||w.to===s.id).map(w=>w.id).join(', ')||'unconnected'}</title><circle class="socket-target" cx="${s.x}" cy="${s.y}" r="${s.radius+5}" fill="${visible?'#ffce4d28':'transparent'}" stroke="${visible?(isSelected?'#0879ff':'#e0a700'):'transparent'}" stroke-width="2"/>${visible?`<path d="M ${s.x-8} ${s.y} h16 M ${s.x} ${s.y-8} v16" stroke="#1157b6" stroke-width="1.6" pointer-events="none"/><text x="${s.x+23}" y="${s.y-15}" font-size="12" font-weight="600" font-family="Arial" fill="#063969" stroke="#ffffff" stroke-width="3" paint-order="stroke" pointer-events="none">${E(s.id)}</text>`:''}</g>`;
 }).join('');
 if(mode==='map'&&mapKind==='controls'&&!manual)text+=kit.controls.map(c=>`<g data-map-control="${c.id}" class="socket"><circle cx="${c.x}" cy="${c.y}" r="${c.radius}" fill="#ffce4d25" stroke="${c.id===selected?'#0879ff':'#e0a700'}" stroke-width="2"/><path d="M ${c.x-9} ${c.y} h18 M ${c.x} ${c.y-9} v18" stroke="#0656b3" stroke-width="2"/><text x="${c.x+c.radius+4}" y="${c.y-12}" font-family="Arial" font-size="12" font-weight="bold" fill="#063969" stroke="white" stroke-width="3" paint-order="stroke">${E(c.id)}</text></g>`).join('');
 if(!manual&&searchIds.has(selected)&&selection?.type==='control'){const c=resolve(selected);text+=`<circle cx="${c.x}" cy="${c.y}" r="${c.radius+8}" fill="none" stroke="#ffbf00" stroke-width="4"/>`;}
 text+=tableSvg(project,kit,!manual&&mode==='design');
 text+=signatureSvg(sceneHeight()-43);
 if(drag?.kind==='connect'&&drag.current){const a=resolve(drag.id);text+=`<path d="M ${a.x} ${a.y} Q ${a.x+70} ${a.y-60} ${drag.current.x} ${drag.current.y}" fill="none" stroke="${color}" stroke-width="6" stroke-dasharray="10 6"/>`;}
 svg.innerHTML=text;viewbox();
 if(mode==='run'&&$('#signal-readout'))$('#signal-readout').innerHTML=signalPanel(sim);
}
function leftPanel(){
 let body=`<div class="section"><h2>Experiment</h2><select id="experiment-select" aria-label="Load example experiment"><option value="">Choose a template…</option>${experiments.map(e=>`<option value="${e.id}">${E(e.title)}</option>`).join('')}</select><p class="hint">${E(project.description)}</p><button class="wide small" data-action="duplicate">Duplicate experiment</button></div>`;
 if(mode==='map')body+=`<div class="section"><h2>Map editor</h2><div class="map-help">Move the crosshair to the exact center of a socket. Connected plugs follow it automatically.</div><select id="map-kind" aria-label="Calibration layer"><option value="sockets" ${mapKind==='sockets'?'selected':''}>Socket centers</option><option value="controls" ${mapKind==='controls'?'selected':''}>Buttons, switches & indicators</option><option value="zones" ${mapKind==='zones'?'selected':''}>Routing keep-out zones</option></select><label class="row"><input type="checkbox" id="grid-toggle" ${grid?'checked':''}/> Snap to 16px grid</label><label class="row"><input type="checkbox" id="zones-toggle" ${showZones?'checked':''}/> Show routing zones</label><button class="primary wide" data-action="save-calibration">Save calibration</button><div class="row" style="margin-top:8px"><button class="small" data-action="export-calibration">Export</button><button class="small" data-action="import-calibration">Import</button></div><button class="small wide" data-action="export-definition" style="margin-top:8px">Download kit-definition.ts</button><p class="hint">Arrow keys: 1px · Shift + arrow: 10px. Positions save with your project. Save calibration applies them to new projects on this browser.</p></div>`;
 else if(mode==='design')body+=`<div class="section"><h2>Patch leads</h2><button class="primary wide" data-action="add">＋ Add cable</button><button class="wide" data-action="add-ethernet" style="margin-top:8px">${project.ethernet?'Ethernet properties':'＋ Ethernet / TIA Portal'}</button><label>Next cable color</label><div class="chips">${palette.map(c=>`<button class="color-chip ${c===color?'selected':''}" data-color="${c}" style="background:${c}" aria-label="Cable color ${c}"></button>`).join('')}</div><p class="hint">Click two sockets, or drag between them.</p></div>`;
 else body+=`<div class="section"><h2>Live inputs</h2><div id="signal-readout">${signalPanel(simulate(project,kit))}</div><button class="wide" data-action="release-emergency">Release Emergency</button><p class="hint">Contact and wiring simulation. No Siemens PLC program is executed.</p><p class="hint">Pulse events: <b id="pulse-events">${pulseCount}</b></p></div>`;
 body+=`<div class="section"><h2>Connections <span class="badge">${project.wires.length}</span></h2>${project.wires.length?project.wires.map(w=>`<div class="connection ${selection?.id===w.id?'selected':''}" data-select-wire="${w.id}" role="button" tabindex="0"><span class="swatch" style="background:${w.color}"></span><div><b>${E(w.label||w.id)}</b><small>${E(resolve(w.from)?.label||w.from)}<br>${E(resolve(w.to)?.label||w.to)}</small></div><span class="end">${w.locked?'▣':w.hidden?'hidden':''}</span></div>`).join(''):'<p class="hint">No leads yet. Choose two sockets on the panel.</p>'}</div>`;
 body+=`<div class="section"><h2>Find component</h2><input id="component-search" placeholder="Start, I0.2, TP1…" value="${E(search)}" aria-label="Search sockets and controls"/><div class="search-results" id="search-results">${searchResults()}</div></div><div class="section"><button class="wide" data-action="table">Connection table</button><label class="row"><input type="checkbox" id="wire-labels" ${project.settings.labels?'checked':''}/> Wire labels</label></div>`;
 if(project.ethernet)body+=`<div class="section"><h2>Programming cable</h2><button class="wide" data-action="select-ethernet">ETH1 · TIA Portal / PROFINET</button><p class="hint">RJ45 cable to ${E(project.ethernet.deviceLabel||'Programming PC')}. Diagram only.</p></div>`;
 const warns=validate(project,kit);if(warns.length)body+=`<h2>Wiring checks</h2>${warns.map(w=>`<div class="warn">${E(w)}</div>`).join('')}`;return body;
}
function signalPanel(sim){return `<div class="signal-grid">${sim.inputs.map((v,i)=>`<div class="signal ${v?'on':''}">I0.${i} · ${v}</div>`).join('')}</div><div class="kv"><span>AI0</span><b>${sim.analog.AI0.toFixed(2)} V</b></div><div class="kv"><span>AI1</span><b>${sim.analog.AI1.toFixed(2)} V</b></div><div class="kv"><span>Kit power</span><b>${sim.powered?'ON':'OFF'}</b></div>${sim.conflicts.map(c=>`<div class="warn">${E(c)}</div>`).join('')}`;}
function searchResults(){return search?[...kit.sockets,...kit.controls].filter(c=>(c.id+' '+c.label).toLowerCase().includes(search.toLowerCase())).slice(0,25).map(c=>`<div class="search-result" data-select-component="${c.id}">${E(c.label)}<small>${c.id} · ${E(c.group||c.type)}</small></div>`).join(''):'<p class="hint">Search highlights matching parts.</p>'}
function rightPanel(){
 if(selection?.type==='ethernet')return ethernetPanel();
 if(selection?.type==='table')return tablePanel();
 if(selection?.type==='wire'){
  const w=project.wires.find(w=>w.id===selection.id);if(!w)return emptyPanel();
  return `<h2>Patch lead properties</h2><span class="badge">${w.id}</span><div class="property-title">${E(w.label||w.id)}</div><label>Label</label><input data-wire-prop="label" value="${E(w.label)}"/><label>Color</label><div class="row"><input type="color" data-wire-prop="color" value="${w.color}"/><span class="hint">${w.color}</span></div><label>From socket</label><select data-wire-prop="from">${options(w.from)}</select><label>To socket</label><select data-wire-prop="to">${options(w.to)}</select><button class="wide small" data-action="reverse" style="margin-top:9px">Reverse endpoints</button><label>Function</label><input data-wire-prop="function" value="${E(w.function)}"/><label>Notes</label><textarea data-wire-prop="notes">${E(w.notes)}</textarea><div class="divider"></div><div class="row"><button data-action="route-selected" ${mode==='run'||w.locked?'disabled':''}>Auto route</button><button data-action="waypoint" ${mode==='run'||w.locked?'disabled':''}>Add bend</button></div><p class="hint">Drag the yellow route handles. Double-click a handle to remove it, or double-click the lead to add one. Drag a plug to reconnect.</p><label class="row"><input type="checkbox" data-wire-prop="locked" ${w.locked?'checked':''}/> Lock route & endpoints</label><label class="row"><input type="checkbox" data-wire-prop="hidden" ${w.hidden?'checked':''}/> Hide cable</label><div class="kv"><span>Routing</span><b>${E(w.route||'manual')}</b></div><div class="row"><button data-action="duplicate-wire">Duplicate</button><button data-action="delete-wire" class="danger" ${mode==='run'?'disabled':''}>Delete lead</button></div>`;
 }
 const c=selection?resolve(selection.id):null;if(!c)return emptyPanel();
 const isSocket=selection.type==='socket',isZone=selection.type==='zone';let text=`<h2>${mode==='map'?'Calibration':'Component properties'}</h2><span class="badge">${E(c.group||c.type||'Routing zone')}</span><div class="property-title">${E(c.label)}</div><div class="property-type">${c.id}</div>`;
 if(mode==='map'){text+=`<label>Center position · image pixels</label><div class="row"><div><label>X</label><input type="number" data-calibration="x" value="${c.x}" min="0" max="1448" step=".5"/></div><div><label>Y</label><input type="number" data-calibration="y" value="${c.y}" min="0" max="1086" step=".5"/></div></div>`;
 if(isZone)text+=`<div class="row"><div><label>Width</label><input type="number" data-calibration="w" value="${c.w}" min="8" max="1448"/></div><div><label>Height</label><input type="number" data-calibration="h" value="${c.h}" min="8" max="1086"/></div></div>`;
 else text+=`<label>Interaction radius</label><input type="number" data-calibration="radius" value="${c.radius}" min="5" max="100"/>`;
 text+=`<div class="row" style="margin-top:12px"><button data-action="nudge-left">←</button><button data-action="nudge-up">↑</button><button data-action="nudge-down">↓</button><button data-action="nudge-right">→</button></div><div class="row" style="margin-top:12px"><button data-action="reset-position">Reset position</button><button class="primary" data-action="save-calibration">Save</button></div><p class="hint">Drag this center on the panel, or enter exact coordinates. The background stays fixed.</p><div class="divider"></div>`;
 }
 if(isZone)return text;
 if(isSocket){const wires=project.wires.filter(w=>w.from===c.id||w.to===c.id);text+=`<div class="kv"><span>Electrical role</span><b>${E(c.electricalType)}</b></div><div class="kv"><span>Connected</span><b>${wires.map(w=>w.id).join(', ')||'—'}</b></div><div class="kv"><span>Signal</span><b>${Number(simulate(project,kit).signals[c.id]||0).toFixed(2)}</b></div><div class="kv"><span>Position</span><b>${c.x}, ${c.y}</b></div>${c.electricalVerified===false?'<p class="hint unverified">Terminal electronics need verification from the kit schematic.</p>':''}<label>Display label</label><input data-label-edit value="${E(c.label)}"/><label>Allowed leads</label><input data-calibration="maxPlugs" type="number" min="1" max="8" value="${c.maxPlugs}"/>${mode==='design'?`<button class="primary wide" data-action="connect-selected" style="margin-top:14px">Connect from this socket</button>`:''}`;
 }else{
  const v=project.states[c.id]||0;text+=`<div class="kv"><span>Type</span><b>${E(c.type)}</b></div>${c.relatedSocket?`<div class="kv"><span>Related socket</span><b>${E(c.relatedSocket)}</b></div>`:''}`;
  if(c.type==='potentiometer')text+=`<label>Position · ${v.toFixed(1)}%</label><input type="range" data-control-range="${c.id}" min="0" max="100" step=".1" value="${v}"/><div class="kv"><span>Analog voltage</span><b>${(v/10).toFixed(2)} V</b></div><p class="hint">Drag vertically on the knob; use the wheel while selected.</p>`;
  else if(['momentary','emergency','toggle','selector','sensor'].includes(c.type)){const label=c.type==='emergency'?(v?'Latched':'Released'):c.type==='momentary'?(v?'Pressed':'Released'):c.type==='selector'?(v?'B':'A'):(v?'ON':'OFF');text+=`<div class="kv"><span>State</span><b>${label}</b></div>`;if(c.type==='momentary')text+=`<button class="wide primary" data-hold="${c.id}">Hold ${E(c.label)}</button>`;else if(c.type==='emergency')text+=`<button class="wide ${v?'':'primary'}" data-action="${v?'release-emergency':'emergency'}">${v?'Release Emergency':'Latch Emergency'}</button>`;else text+=`<button class="wide" data-toggle-control="${c.id}">${c.type==='selector'?'Switch A / B':'Toggle state'}</button>`;}
  else text+=`<p class="hint">This indicator reflects its connected signal in simulation.</p>`;
 }
 return text;
}
function emptyPanel(){return `<h2>Properties</h2><div class="empty-property"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m13 8 25 17-13 4-6 14z"/><circle cx="24" cy="24" r="22" stroke-dasharray="3 5"/></svg><h3>Select a lead or component</h3><p class="hint">Inspect wiring, adjust cable bends, or operate the controls.</p></div><div class="section"><h2>Panel navigation</h2><p class="hint">Wheel to zoom. Middle mouse, or Space + drag to pan.</p><p class="hint">F: fit · 1: 100%<br>Ctrl+Z / Ctrl+Y: undo / redo<br>Ctrl+S: save project</p></div><div class="section"><h2>Correct socket positions</h2><p class="hint">Open Calibrate to drag socket centers, buttons and switches onto the exact image positions.</p><button data-mode="map" class="wide">Open calibration</button></div>`}
function tablePanel(){const t=project.table;return `<h2>Connection table</h2><p class="hint">Drag the table on the canvas. It also appears in the table export preset.</p><div class="table-options"><label class="check"><input type="checkbox" data-table-prop="show" ${t.show?'checked':''}/> Show table</label><label>Title</label><input data-table-prop="title" value="${E(t.title)}"/><div class="row"><div><label>X</label><input type="number" data-table-prop="x" value="${t.x}" min="0" max="1448"/></div><div><label>Y</label><input type="number" data-table-prop="y" value="${t.y}" min="0" max="2500"/></div></div><label>Width</label><input type="number" data-table-prop="width" value="${t.width}" min="300" max="1400"/><label>Text size</label><input type="number" data-table-prop="fontSize" value="${t.fontSize}" min="12" max="32"/><label>Style</label><select data-table-prop="style"><option value="light" ${t.style==='light'?'selected':''}>Light</option><option value="dark" ${t.style==='dark'?'selected':''}>Dark</option></select><label class="check"><input type="checkbox" data-table-prop="useIds" ${t.useIds?'checked':''}/> Show socket IDs</label><label>Columns</label>${['Wire','From','To','Color','Function','Notes'].map(c=>`<label class="check"><input type="checkbox" data-table-column="${c}" ${t.columns.includes(c)?'checked':''}/> ${c}</label>`).join('')}</div>`}
function modal(title,content,actions=''){const d=$('#modal');d.innerHTML=`<div class="modal-head"><h3>${E(title)}</h3><button data-action="close-modal" aria-label="Close">×</button></div>${content}${actions?`<div class="modal-actions">${actions}</div>`:''}`;d.showModal();}
function saveProject(downloadFile=false){project.author={...AUTHOR};try{saveNamed(project);toast('Project saved on this browser.');if(downloadFile)download(`${project.title.replace(/[^a-z0-9_-]+/gi,'_')}.sabronpro.json`,JSON.stringify(project,null,2));}catch{download(`${project.title.replace(/[^a-z0-9_-]+/gi,'_')}.sabronpro.json`,JSON.stringify(project,null,2));toast('Browser storage is unavailable. Project downloaded instead.');}}
function calibrate(id,prop,value,record=true){const c=resolve(id);if(!c)return;const v=Number(value);if(!Number.isFinite(v))return;const ranges={x:[0,1448],y:[0,1086],radius:[5,100],w:[8,1448],h:[8,1086],maxPlugs:[1,8]};const [lo,hi]=ranges[prop]||[-Infinity,Infinity];if(record)commit();project.calibration[id]={...(project.calibration[id]||{}),x:c.x,y:c.y,[prop]:Math.max(lo,Math.min(hi,v))};kit=calibratedKit(project.calibration);followSocket(id);changed();}
function followSocket(id){const c=resolve(id);if(project.ethernet?.portId===id)project.ethernet.waypoints[0]={x:c.x,y:c.y};for(const w of project.wires){if(!w.waypoints?.length)continue;if(w.from===id)w.waypoints[0]={x:c.x,y:c.y};if(w.to===id)w.waypoints[w.waypoints.length-1]={x:c.x,y:c.y};}}
function saveCalibration(){try{calibration=clone(project.calibration);localStorage.setItem('sabronpro:calibration',JSON.stringify(calibration));saveProject();toast('Calibration saved. New projects will use these positions.');}catch{toast('Storage unavailable. Export calibration to keep your changes.');}}
function removeWire(){if(selection?.type==='ethernet'){if(mode==='run')return;commit();project.ethernet=null;selection=null;changed();return;}if(selection?.type!=='wire'||mode==='run')return;commit();project.wires=project.wires.filter(w=>w.id!==selection.id);selection=null;changed()}
const actions={
 'credits':()=>modal('Crafted with love',`<div class="credits-card"><div class="credits-hearts" aria-hidden="true">✦ ♥ ✧ ♥ ✦</div><span class="badge">SABRONPRO WIRING STUDIO · v${AUTHOR.version}</span><h3>Made with love <span class="heart">♥</span></h3><div class="author-name">Eng. Mahmoud Shreef</div><p>Created for engineers, experiment makers, and the joy of building something that works.</p><div class="credits-rule"></div><strong>${AUTHOR.copyright}</strong><p class="hint">Software authorship and credit: Eng. Mahmoud Shreef. Attribution accompanies project files, diagrams and the source package.</p><p class="hint">Manufacturer names, trademarks and third-party materials belong to their respective owners.</p></div>`),
 'add-ethernet':()=>project.ethernet?select('ethernet','ETH1'):addEthernet(),
 'select-ethernet':()=>select('ethernet','ETH1'),
 'route-ethernet':()=>{if(!project.ethernet||project.ethernet.locked||mode==='run')return;commit();routeEthernet();changed()},
 'bend-ethernet':()=>{const e=project.ethernet;if(!e||e.locked||mode==='run')return;commit();const i=Math.max(1,Math.floor(e.waypoints.length/2)),a=e.waypoints[i-1],b=e.waypoints[i];e.waypoints.splice(i,0,{x:(a.x+b.x)/2,y:(a.y+b.y)/2-35});e.route='manual';changed()},
 'delete-ethernet':()=>{if(mode!=='run'){commit();project.ethernet=null;selection=null;changed()}},
 'new':()=>modal('Start a new experiment','<p>Your current work is recovered locally. Save a named copy or download it before starting over.</p>','<button data-action="close-modal">Cancel</button><button class="primary" data-action="confirm-new">New blank project</button>'),
 'confirm-new':()=>{$('#modal').close();newProject()},
 'undo':()=>snapshotUndo(), 'redo':()=>snapshotUndo(true),
 'open':()=>{const projects=listProjects();modal('Open project',`<button class="primary wide" data-action="open-file">Open a project JSON file</button><div class="divider"></div><h2>Saved on this browser</h2>${Object.values(projects).length?Object.values(projects).map(p=>`<button class="wide" style="margin:5px 0;text-align:left" data-open-saved="${E(p.projectId)}">${E(p.title)}<small style="display:block;color:var(--muted);margin-top:5px">${p.wires.length} leads · ${new Date(p.savedAt).toLocaleString()}</small></button>`).join(''):'<p>No saved projects yet.</p>'}`)},
 'open-file':()=>{$('#file-input').dataset.kind='project';$('#file-input').click()},
 'save':()=>saveProject(true),
 'save-as':()=>modal('Save as',`<label>Experiment title</label><input id="save-as-title" value="${E(project.title+' · copy')}"/>`,'<button data-action="close-modal">Cancel</button><button data-action="confirm-save-as" class="primary">Save copy</button>'),
 'confirm-save-as':()=>{commit();project.projectId=crypto.randomUUID();project.title=$('#save-as-title').value||project.title;$('#modal').close();changed();saveProject(true)},
 'duplicate':()=>{commit();project.projectId=crypto.randomUUID();project.title+=' · copy';changed();saveProject();},
 'add':()=>modal('Add patch lead',`<label>From socket</label><select id="add-from">${options(pending||'START_NO',true)}</select><label>To socket</label><select id="add-to">${options('I0_2',true)}</select><div class="row"><div><label>Label (optional)</label><input id="add-label" placeholder="W4"/></div><div><label>Cable color</label><input type="color" id="add-color" value="${color}"/></div></div>`,'<button data-action="close-modal">Cancel</button><button data-action="create-wire" class="primary">Create + auto route</button>'),
 'create-wire':()=>{if(addWire($('#add-from').value,$('#add-to').value,$('#add-color').value,$('#add-label').value))$('#modal').close()},
 'route-all':()=>{if(mode==='run')return;commit();const routed=[];for(const w of project.wires){if(!w.locked)autoroute(w,routed);routed.push(w)}if(project.ethernet&&!project.ethernet.locked)routeEthernet();changed();toast('Leads routed around the panel keep-out zones.');},
 'route-selected':()=>{const w=project.wires.find(w=>w.id===selection?.id);if(w&&!w.locked&&mode!=='run'){commit();autoroute(w);changed()}},
 'reverse':()=>{const w=project.wires.find(w=>w.id===selection?.id);if(!w||mode==='run'||w.locked)return;commit();[w.from,w.to]=[w.to,w.from];w.waypoints.reverse();changed()},
 'waypoint':()=>{const w=project.wires.find(w=>w.id===selection?.id);if(!w||mode==='run'||w.locked)return;commit();let i=Math.max(1,Math.floor(w.waypoints.length/2)),a=w.waypoints[i-1],b=w.waypoints[i];w.waypoints.splice(i,0,{x:(a.x+b.x)/2,y:(a.y+b.y)/2-25});w.route='manual';changed()},
 'delete-wire':removeWire,
 'duplicate-wire':()=>{const w=project.wires.find(w=>w.id===selection?.id);if(w&&mode!=='run')addWire(w.from,w.to,w.color)},
 'connect-selected':()=>{pending=selection.id;render()},
 'table':()=>select('table','table'),
 'save-calibration':saveCalibration,
 'export-calibration':()=>download('SabronPro-calibration.json',JSON.stringify({kitId:KIT.id,version:1,calibration:project.calibration},null,2)),
 'import-calibration':()=>{$('#file-input').dataset.kind='calibration';$('#file-input').click()},
 'export-definition':()=>{const definition={...KIT,sockets:kit.sockets,controls:kit.controls,obstacles:kit.obstacles};download('kit-definition.ts',`// Calibrated SabronPro definition in original image coordinates.\nexport const kitDefinition = ${JSON.stringify(definition,null,2)} as const;\n`,'text/plain')},
 'reset-position':()=>{if(!selection)return;commit();delete project.calibration[selection.id];kit=calibratedKit(project.calibration);followSocket(selection.id);changed()},
 'nudge-left':()=>nudge(-1,0),'nudge-right':()=>nudge(1,0),'nudge-up':()=>nudge(0,-1),'nudge-down':()=>nudge(0,1),
 'release-emergency':()=>setState('EMERGENCY_BUTTON',0), 'emergency':()=>setState('EMERGENCY_BUTTON',1),
 'zoom-in':()=>zoomAt(zoom*1.2), 'zoom-out':()=>zoomAt(zoom/1.2), 'fit':()=>{zoom=1;pan={x:0,y:0};viewbox()},'one':()=>{zoom=1;pan={x:0,y:0};viewbox()},
 'manual':()=>{manual=!manual;render()},
 'left':()=>$('#left').classList.toggle('open'),'right':()=>$('#right').classList.toggle('open'),
 'close-modal':()=>$('#modal').close(),
 'export':()=>modal('Export for your manual',`<label>Diagram preset</label><select id="export-preset"><option value="table">Diagram + connection table</option><option value="labels">Diagram + wire labels</option><option value="no-labels">Diagram without labels</option><option value="clean">Clean diagram</option><option value="snapshot">Simulation state snapshot</option></select><label>Format</label><select id="export-format"><option value="png">PNG image</option><option value="svg">SVG with vector leads and plugs</option><option value="pdf">Print / Save as PDF</option></select><label>PNG resolution</label><select id="export-scale"><option value="1">Original · 1448 px wide</option><option value="2" selected>2× · 2896 px wide</option><option value="4">4× · 5792 px wide</option></select><p class="hint">Includes the original panel image. Editing handles, calibration markers and toolbars are omitted.</p>`,'<button data-action="close-modal">Cancel</button><button class="primary" data-action="do-export">Export</button>'),
 'do-export':async()=>{const options={format:$('#export-format').value,preset:$('#export-preset').value,scale:Number($('#export-scale').value)};$('#modal').close();toast('Preparing diagram…');try{await exportDiagram(project,kit,options);toast(options.format==='pdf'?'Choose Save as PDF in the print dialog.':'Diagram exported.')}catch(e){toast(e.message)}},
 'help':()=>modal('Use your SabronPro panel',`<h3>1 · Wire the kit</h3><p>In Design, click two sockets or use Add cable. Select a lead to edit endpoints, color, notes or bends. Drag its yellow handles, or drag a plug onto a new socket.</p><h3>2 · Correct the map</h3><p>In Calibrate, choose Socket centers. Drag a crosshair onto the real socket, use arrow keys for precision, or enter X/Y in Properties. Save calibration remembers your positions. Export calibration keeps a portable backup.</p><h3>3 · Run the controls</h3><p>Run keeps wiring fixed. Hold START, STOP, RESET or PULSE; click toggles and selectors; drag knobs. Emergency latches until you select Release Emergency.</p><h3>4 · Save & export</h3><p>Save stores a browser copy and downloads a project JSON. Open it on another computer. Export generates PNG, SVG or a print-ready diagram. Local recovery is tied to this browser and address.</p><p class="hint">The simulator models contacts, sources and wiring. It does not execute Siemens ladder logic or communicate with physical hardware.</p>`)
};
function nudge(dx,dy){if(mode!=='map'||!selection)return;const c=resolve(selection.id);if(!c)return;commit();project.calibration[c.id]={...(project.calibration[c.id]||{}),x:Math.max(0,Math.min(1448,c.x+dx)),y:Math.max(0,Math.min(1086,c.y+dy))};kit=calibratedKit(project.calibration);followSocket(c.id);changed()}
function point(event){const p=new DOMPoint(event.clientX,event.clientY);return p.matrixTransform($('#canvas').getScreenCTM().inverse())}
function zoomAt(value,p){let next=Math.max(.5,Math.min(5,value));if(!p)p={x:pan.x+724/zoom,y:pan.y+sceneHeight()/2/zoom};const ratio=zoom/next;pan={x:p.x-(p.x-pan.x)*ratio,y:p.y-(p.y-pan.y)*ratio};zoom=next;viewbox()}
function nearest(p,type='banana_socket'){const choices=kit.sockets.filter(s=>s.type===type).map(s=>({s,d:Math.hypot(s.x-p.x,s.y-p.y)})).sort((a,b)=>a.d-b.d);return choices[0]?.d<34?choices[0].s:null}
function capture(e){$('#canvas').setPointerCapture(e.pointerId)}
function bind(){
 document.addEventListener('click',async e=>{
  const a=e.target.closest('[data-action]');if(a){const fn=actions[a.dataset.action];if(fn)await fn();return}
  const m=e.target.closest('[data-mode]');if(m){setMode(m.dataset.mode);return}
  const colorButton=e.target.closest('[data-color]');if(colorButton){color=colorButton.dataset.color;render();return}
  const wire=e.target.closest('[data-select-wire]');if(wire){select('wire',wire.dataset.selectWire);return}
  const c=e.target.closest('[data-select-component]');if(c){const id=c.dataset.selectComponent;selection={type:kit.sockets.some(s=>s.id===id)?'socket':'control',id};pending=null;render();return}
  const t=e.target.closest('[data-toggle-control]');if(t){setState(t.dataset.toggleControl,project.states[t.dataset.toggleControl]?0:1);return}
  const saved=e.target.closest('[data-open-saved]');if(saved){const p=listProjects()[saved.dataset.openSaved];if(p){commit();project=clone(p);selection=null;$('#modal').close();changed();toast('Saved project opened.');}return}
 });
 document.addEventListener('change',e=>{
  const el=e.target;if(el.id==='project-title'){commit();project.title=el.value||'Untitled experiment';changed();return}
  if(el.id==='experiment-select'){const exp=experiments.find(x=>x.id===el.value);if(exp)newProject(exp);return}
  if(el.dataset.controlRange){changed();return}
  if(el.id==='map-kind'){mapKind=el.value;if(mapKind==='zones')showZones=true;selection=null;render();return}
  if(el.id==='zones-toggle'){showZones=el.checked;renderScene();return}if(el.id==='grid-toggle'){grid=el.checked;return}
  if(el.id==='wire-labels'){commit();project.settings.labels=el.checked;changed();return}
  if(el.dataset.ethernetProp){const cable=project.ethernet;if(!cable||mode==='run')return;const prop=el.dataset.ethernetProp;if(cable.locked&&['x','y'].includes(prop)){render();return}commit();if(['x','y'].includes(prop)){const n=Number(el.value);if(Number.isFinite(n)){cable.endpoint[prop]=Math.max(prop==='x'?85:20,Math.min(prop==='x'?1360:1080,n));routeEthernet();}}else cable[prop]=el.type==='checkbox'?el.checked:el.value;changed();return}
  if(el.dataset.wireProp){const w=project.wires.find(w=>w.id===selection?.id);if(!w||mode==='run')return;const prop=el.dataset.wireProp;if(w.locked&&!['locked','hidden','label','notes','function','color'].includes(prop)){render();return}commit();w[prop]=el.type==='checkbox'?el.checked:el.value;if(prop==='from'||prop==='to')autoroute(w);changed();return}
  if(el.dataset.calibration){if(selection)calibrate(selection.id,el.dataset.calibration,el.value);return}
  if(el.hasAttribute('data-label-edit')){const c=resolve(selection.id);commit();project.calibration[c.id]={...(project.calibration[c.id]||{}),x:c.x,y:c.y,label:el.value};changed();return}
  if(el.dataset.tableProp){commit();project.table[el.dataset.tableProp]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;changed();return}
  if(el.dataset.tableColumn){commit();let cols=project.table.columns.filter(c=>c!==el.dataset.tableColumn);if(el.checked)cols.push(el.dataset.tableColumn);project.table.columns=cols.length?cols:['Wire'];changed();return}
 });
 document.addEventListener('input',e=>{const el=e.target;if(el.id==='component-search'){search=el.value;$('#search-results').innerHTML=searchResults();renderScene();}if(el.dataset.controlRange){if(!drag)commit();project.states[el.dataset.controlRange]=Number(el.value);persist(project);renderScene();}});
 document.addEventListener('pointerdown',e=>{const h=e.target.closest('[data-hold]');if(h){const id=h.dataset.hold;commit();project.states[id]=1;renderScene();drag={kind:'hold',id};h.setPointerCapture(e.pointerId);if(id==='PULSE_BUTTON'){pulseCount++;$('#pulse-events')&&($('#pulse-events').textContent=pulseCount)}}});
 document.addEventListener('pointerup',e=>{if(drag?.kind==='hold'){project.states[drag.id]=0;drag=null;changed();}});
 const svg=$('#canvas');
 svg.addEventListener('pointerdown',e=>{
  const p=point(e),el=e.target;
  if(e.button===1||space){e.preventDefault();drag={kind:'pan',start:p,pan:{...pan},client:{x:e.clientX,y:e.clientY}};capture(e);return}
  if(e.button!==0)return;
  if(mode==='map'){
   const s=el.closest('[data-socket]'),c=el.closest('[data-map-control]'),z=el.closest('[data-zone]');let id,type;
   if(mapKind==='sockets'&&s){id=s.dataset.socket;type='socket'}else if(mapKind==='controls'&&c){id=c.dataset.mapControl;type='control'}else if(mapKind==='zones'&&z){id=z.dataset.zone;type='zone'}
   if(id){selection={id,type};commit();const item=resolve(id);drag={kind:'calibration',id,start:p,origin:{x:item.x,y:item.y}};capture(e);render();return}
  }
  const ctrl=el.closest('[data-control]');if(ctrl&&mode!=='map'){
   const id=ctrl.dataset.control,c=resolve(id);selection={id,type:'control'};
   if(c.type==='momentary'){commit();project.states[id]=1;drag={kind:'momentary',id};capture(e);if(id==='PULSE_BUTTON')pulseCount++;changed();return}
   if(c.type==='emergency'){if(!project.states[id]){commit();project.states[id]=1;}changed();return}
   if(c.type==='potentiometer'){commit();drag={kind:'pot',id,start:p,value:project.states[id]||0};capture(e);render();return}
   if(['toggle','selector','sensor'].includes(c.type)){setState(id,project.states[id]?0:1);return}render();return;
  }
  if(mode!=='design')return;
  const ew=el.closest('[data-ethernet-waypoint]');if(ew&&project.ethernet&&!project.ethernet.locked){commit();selection={type:'ethernet',id:'ETH1'};drag={kind:'ethernet-waypoint',index:Number(ew.dataset.ethernetWaypoint)};capture(e);render();return}
  const ed=el.closest('[data-ethernet-device]');if(ed&&project.ethernet&&!project.ethernet.locked){commit();selection={type:'ethernet',id:'ETH1'};drag={kind:'ethernet-device',start:p,origin:{...project.ethernet.endpoint}};capture(e);render();return}
  const eth=el.closest('[data-ethernet]');if(eth){select('ethernet','ETH1');return}
  const wp=el.closest('[data-waypoint]');if(wp){const w=project.wires.find(v=>v.id===wp.dataset.wire);if(w.locked)return;commit();selection={type:'wire',id:w.id};drag={kind:'waypoint',id:w.id,index:Number(wp.dataset.waypoint)};capture(e);render();return}
  const endpoint=el.closest('[data-endpoint]');if(endpoint){const w=project.wires.find(v=>v.id===endpoint.dataset.wire);if(w.locked)return;selection={type:'wire',id:w.id};drag={kind:'endpoint',id:w.id,end:endpoint.dataset.endpoint,type:resolve(w[endpoint.dataset.endpoint]).type,current:p};capture(e);render();return}
  const socket=el.closest('[data-socket]');if(socket&&resolve(socket.dataset.socket)?.type==='rj45_socket'){socketClick(socket.dataset.socket);return}if(socket){drag={kind:'connect',id:socket.dataset.socket,start:p,current:p,moved:false};capture(e);return}
  const tr=el.closest('[data-table-resize]');if(tr){commit();drag={kind:'table-resize',start:p,width:project.table.width};capture(e);return}
  const table=el.closest('[data-table]');if(table){selection={type:'table',id:'table'};commit();drag={kind:'table',start:p,origin:{x:project.table.x,y:project.table.y}};capture(e);render();return}
  const wire=el.closest('[data-wire]');if(wire){select('wire',wire.dataset.wire);return}
  if(mode==='design'){selection=null;pending=null;render()}
 });
 svg.addEventListener('pointermove',e=>{
  const p=point(e);$('#coords').textContent=`X ${p.x.toFixed(0)} · Y ${p.y.toFixed(0)}`;if(!drag)return;
  if(drag.kind==='pan'){const rect=svg.getBoundingClientRect(),factor=Math.max((1448/zoom)/rect.width,(sceneHeight()/zoom)/rect.height);pan={x:drag.pan.x-(e.clientX-drag.client.x)*factor,y:drag.pan.y-(e.clientY-drag.client.y)*factor};viewbox();return}
  if(drag.kind==='calibration'){const c=resolve(drag.id);let x=Math.max(0,Math.min(1448,drag.origin.x+p.x-drag.start.x)),y=Math.max(0,Math.min(1086,drag.origin.y+p.y-drag.start.y));if(grid){x=Math.round(x/16)*16;y=Math.round(y/16)*16}project.calibration[c.id]={...(project.calibration[c.id]||{}),x:Math.round(x*10)/10,y:Math.round(y*10)/10};kit=calibratedKit(project.calibration);followSocket(c.id);renderScene();return}
  if(drag.kind==='pot'){project.states[drag.id]=Math.max(0,Math.min(100,Math.round((drag.value+(drag.start.y-p.y)*.5)*10)/10));renderScene();return}
  if(drag.kind==='connect'){drag.current=p;drag.moved=drag.moved||Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>8;renderScene();return}
  if(drag.kind==='ethernet-waypoint'){project.ethernet.waypoints[drag.index]={x:Math.max(0,Math.min(1448,p.x)),y:Math.max(0,Math.min(1086,p.y))};project.ethernet.route='manual';renderScene();return}
  if(drag.kind==='ethernet-device'){const e=project.ethernet;e.endpoint={x:Math.max(85,Math.min(1360,drag.origin.x+p.x-drag.start.x)),y:Math.max(20,Math.min(1080,drag.origin.y+p.y-drag.start.y))};e.waypoints[e.waypoints.length-1]={...e.endpoint};renderScene();return}
  if(drag.kind==='waypoint'){const w=project.wires.find(w=>w.id===drag.id);w.waypoints[drag.index]={x:grid?Math.round(p.x/16)*16:p.x,y:grid?Math.round(p.y/16)*16:p.y};w.route='manual';renderScene();return}
  if(drag.kind==='endpoint'){drag.current=p;renderScene();const target=nearest(p,drag.type);if(target){$('#status-selection').textContent=`Reconnect to ${target.label}`;svg.insertAdjacentHTML('beforeend',`<circle cx="${target.x}" cy="${target.y}" r="25" fill="#ffcf4940" stroke="#b47b00" stroke-width="3" pointer-events="none"/>`)}return}
  if(drag.kind==='table'){project.table.x=Math.max(0,Math.min(1440,drag.origin.x+p.x-drag.start.x));project.table.y=Math.max(0,Math.min(2400,drag.origin.y+p.y-drag.start.y));renderScene();return}
  if(drag.kind==='table-resize'){project.table.width=Math.max(300,Math.min(1400,drag.width+p.x-drag.start.x));renderScene();return}
 });
 function release(e,cancel=false){if(!drag)return;const d=drag,p=point(e);drag=null;
  if(d.kind==='momentary'){project.states[d.id]=0;changed();return}
  if(d.kind==='connect'){if(cancel){render();return}if(d.moved){const target=nearest(p,resolve(d.id).type);if(target&&target.id!==d.id)addWire(d.id,target.id);else{toast('Drop on a compatible socket to connect.');render()}}else socketClick(d.id);return}
  if(d.kind==='endpoint'){if(!cancel){const target=nearest(p,d.type),w=project.wires.find(w=>w.id===d.id);if(target&&target.id!==w[d.end==='from'?'to':'from']){commit();w[d.end]=target.id;autoroute(w);changed();return}}render();toast('Endpoint kept on its original socket.');return}
  if(d.kind!=='pan')changed();else renderScene();
 }
 svg.addEventListener('pointerup',e=>release(e));svg.addEventListener('pointercancel',e=>release(e,true));
 svg.addEventListener('contextmenu',e=>{e.preventDefault();const c=e.target.closest('[data-control]');if(c?.dataset.control==='EMERGENCY_BUTTON')setState('EMERGENCY_BUTTON',0)});
 svg.addEventListener('dblclick',e=>{if(mode!=='design')return;const ew=e.target.closest('[data-ethernet-waypoint]');if(ew){if(project.ethernet&&!project.ethernet.locked){commit();project.ethernet.waypoints.splice(Number(ew.dataset.ethernetWaypoint),1);project.ethernet.route='manual';changed()}return;}const wp=e.target.closest('[data-waypoint]');if(wp){const w=project.wires.find(w=>w.id===wp.dataset.wire);if(!w.locked){commit();w.waypoints.splice(Number(wp.dataset.waypoint),1);w.route='manual';changed()}return}const wire=e.target.closest('[data-wire]');if(wire){const w=project.wires.find(w=>w.id===wire.dataset.wire);if(w.locked)return;const p=point(e);let best=Infinity,index=1;for(let i=1;i<w.waypoints.length;i++){const a=w.waypoints[i-1],b=w.waypoints[i],vx=b.x-a.x,vy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*vx+(p.y-a.y)*vy)/(vx*vx+vy*vy||1))),distance=Math.hypot(p.x-a.x-t*vx,p.y-a.y-t*vy);if(distance<best){best=distance;index=i}}commit();w.waypoints.splice(index,0,{x:p.x,y:p.y});w.route='manual';selection={type:'wire',id:w.id};changed()}});
 svg.addEventListener('wheel',e=>{e.preventDefault();const c=resolve(selection?.id);if(c?.type==='potentiometer'&&mode!=='map'&&e.target.closest('[data-control]')?.dataset.control===c.id){commit();project.states[c.id]=Math.max(0,Math.min(100,(project.states[c.id]||0)-Math.sign(e.deltaY)));changed();return}zoomAt(zoom*Math.exp(-e.deltaY*.0015),point(e));},{passive:false});
 document.addEventListener('keydown',e=>{
  const isInput=['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName);
  if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject(true);return}
  if(isInput)return;
  if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();snapshotUndo(e.shiftKey);return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();snapshotUndo(true);return}
  if(e.code==='Space'){if(e.target.closest('[data-control]')){e.preventDefault();keyboardControl(e.target.closest('[data-control]').dataset.control,true);return}e.preventDefault();space=true;return}
  if(e.key==='Enter'){const s=e.target.closest('[data-socket]'),c=e.target.closest('[data-control]');if(s){socketClick(s.dataset.socket);return}if(c){keyboardControl(c.dataset.control,true);return}const con=e.target.closest('[data-select-wire]');if(con)select('wire',con.dataset.selectWire);return}
  if(e.key==='Delete'){removeWire();return}if(e.key==='Escape'){pending=null;selection=null;drag=null;project.states.START_BUTTON=project.states.STOP_BUTTON=project.states.RESET_BUTTON=project.states.PULSE_BUTTON=0;changed();return}
  if(e.key.toLowerCase()==='f'){actions.fit();return}if(e.key==='1'){actions.one();return}
  if(mode==='map'&&selection&&e.key.startsWith('Arrow')){e.preventDefault();const step=e.shiftKey?10:1;nudge(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0)}
 });
 function keyboardControl(id,pressed){const c=resolve(id);if(!c||mode==='map')return;selection={type:'control',id};if(c.type==='momentary')setState(id,pressed?1:0);else if(pressed&&c.type==='emergency')setState(id,1);else if(pressed&&['toggle','selector','sensor'].includes(c.type))setState(id,project.states[id]?0:1);}
 document.addEventListener('keyup',e=>{if(e.code==='Space')space=false;if(['Enter',' '].includes(e.key)){const c=resolve(selection?.id);if(c?.type==='momentary'&&project.states[c.id])setState(c.id,0,false)}});
 window.addEventListener('blur',()=>{for(const c of kit.controls)if(c.type==='momentary')project.states[c.id]=0;drag=null;space=false;changed()});
 $('#file-input').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5e6)throw Error('Project JSON must be under 5MB.');const p=JSON.parse(await f.text());if(e.target.dataset.kind==='calibration'){if(p.kitId!==KIT.id||!p.calibration)throw Error('Invalid calibration file.');validateImport({...project,calibration:p.calibration},kit);commit();project.calibration=p.calibration;kit=calibratedKit(project.calibration);for(const s of kit.sockets)followSocket(s.id);changed();toast('Calibration loaded. Save to use it for future projects.');}else{validateImport(p,kit);commit();project={...blank(experiments[3]),...p,settings:{labels:true,...p.settings},table:{...blank().table,...p.table},states:{...defaultStates(),...p.states},calibration:p.calibration||{}};selection=null;changed();toast('Project opened.');}if($('#modal').open)$('#modal').close();}catch(err){toast(err.message)}finally{e.target.value=''}});
}
init();
window.SabronPro={getProject:()=>clone(project),getKit:()=>clone(kit),getSignals:()=>simulate(project,kit),addWire,addEthernet,routeEthernet,calibrate:(id,x,y)=>{const c=resolve(id);if(!c||!Number.isFinite(x)||!Number.isFinite(y))throw Error('Unknown component or invalid coordinates');calibrate(id,'x',x);calibrate(id,'y',y);return resolve(id)},setState,setMode,loadExperiment:id=>{const exp=experiments.find(e=>e.id===id);if(!exp)throw Error('Unknown experiment');newProject(exp)},undo:()=>snapshotUndo(),redo:()=>snapshotUndo(true),exportDiagram:opts=>exportDiagram(project,kit,opts)};
if(document.modelContext?.registerTool){
 document.modelContext.registerTool({name:'read_sabronpro_project',description:'Read the current SabronPro wiring, calibration and control states.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.SabronPro.getProject()});
 document.modelContext.registerTool({name:'calibrate_sabronpro_component',description:'Move and save a known socket or control center in original panel pixels.',inputSchema:{type:'object',properties:{id:{type:'string'},x:{type:'number',minimum:0,maximum:1448},y:{type:'number',minimum:0,maximum:1086}},required:['id','x','y'],additionalProperties:false},execute:input=>{if(!input||typeof input.id!=='string'||!Number.isFinite(input.x)||!Number.isFinite(input.y)||input.x<0||input.x>1448||input.y<0||input.y>1086||!resolve(input.id))throw Error('Invalid calibration');return window.SabronPro.calibrate(input.id,input.x,input.y)}});
}

function routeEthernet(){const e=project.ethernet;if(!e)return;const port=resolve(e.portId);e.waypoints=routeWire(port,{id:'PROGRAMMING_PC',...e.endpoint},kit,project.wires,project.wires.length);e.route='auto';}
function addEthernet(){if(mode!=='design'){toast('Switch to Design to add an Ethernet cable.');return}if(project.ethernet){select('ethernet','ETH1');return}commit();project.ethernet={id:'ETH1',portId:'TIA_PROFINET',label:'ETH1',deviceLabel:'Programming PC',endpoint:{x:1270,y:1040},color:'#12a367',notes:'TIA Portal / PROFINET programming cable · diagram only',hidden:false,locked:false,waypoints:[],route:'auto'};routeEthernet();selection={type:'ethernet',id:'ETH1'};changed();toast('Ethernet cable connected to the TIA Portal / PROFINET port.');}
function ethernetPanel(){const e=project.ethernet;if(!e)return emptyPanel();return `<h2>Ethernet cable</h2><span class="badge">RJ45 · PROFINET</span><div class="property-title">TIA Portal connection</div><p class="hint">Diagram cable to a programming computer. No live PLC communication.</p><label>Lead label</label><input data-ethernet-prop="label" value="${E(e.label)}"/><label>Computer label</label><input data-ethernet-prop="deviceLabel" value="${E(e.deviceLabel)}"/><label>Cable color</label><input type="color" data-ethernet-prop="color" value="${e.color}"/><div class="kv"><span>Panel port</span><b>TIA_PROFINET</b></div><label>Computer connector position</label><div class="row"><div><label>X</label><input type="number" data-ethernet-prop="x" value="${e.endpoint.x}" min="85" max="1360"/></div><div><label>Y</label><input type="number" data-ethernet-prop="y" value="${e.endpoint.y}" min="20" max="1080"/></div></div><p class="hint">Drag the computer or its RJ45 plug to reposition it. The panel connector follows the calibrated RJ45 port.</p><div class="row"><button data-action="route-ethernet" ${e.locked||mode==='run'?'disabled':''}>Auto route</button><button data-action="bend-ethernet" ${e.locked||mode==='run'?'disabled':''}>Add bend</button></div><p class="hint">Drag yellow bend handles. Double-click a handle to remove it.</p><label>Notes</label><textarea data-ethernet-prop="notes">${E(e.notes)}</textarea><label class="row"><input type="checkbox" data-ethernet-prop="locked" ${e.locked?'checked':''}/> Lock cable</label><label class="row"><input type="checkbox" data-ethernet-prop="hidden" ${e.hidden?'checked':''}/> Hide Ethernet cable</label><button data-action="delete-ethernet" class="danger wide" ${mode==='run'?'disabled':''}>Remove Ethernet cable</button>`;}
