import {curvePath} from '../routing/router.js';
import {escapeHtml} from './render.js';
// RJ45 connectors are deliberately separate from the banana lead renderer and signal graph.
export function rj45Plug(x,y,angle,color,attr=''){
 return `<g ${attr} transform="translate(${x} ${y}) rotate(${angle})" filter="url(#leadShadow)"><rect x="-10" y="-11" width="26" height="22" rx="2" fill="#dbe4e9" fill-opacity=".9" stroke="#283642" stroke-width="1.4"/><rect x="-6" y="-8" width="9" height="16" rx="1" fill="#283640"/>${Array.from({length:8},(_,i)=>`<path d="M -8 ${-7+i*2} H 3" stroke="#e2ba50" stroke-width="1.1"/>`).join('')}<path d="M 2 -12 L 23 -12 L 26 -7 L 11 -7" fill="#eef6fa" fill-opacity=".8" stroke="#788b98"/><path d="M 13 -12 L 37 -9 L 43 -5 L 43 5 L 37 9 L 13 12 Z" fill="${color}" stroke="#172831" stroke-width="1.5"/><path d="M 13 -12 L 37 -9 L 43 -5 L 43 5 L 37 9 L 13 12 Z" fill="url(#plugLight)"/><path d="M 20 -10 V10 M 25 -9 V9 M 30 -9 V9 M 35 -8 V8" stroke="#08261d" stroke-opacity=".4"/><path d="M 16 -9 L 35 -7" stroke="white" stroke-opacity=".6"/></g>`;
}
export function ethernetSvg(project,kit,selected=false,editing=false,interactive=true,labels=true){
 const e=project.ethernet;if(!e||e.hidden)return '';const port=kit.sockets.find(s=>s.id===e.portId);if(!port)return '';
 const target=e.endpoint,points=[{x:port.x,y:port.y},...(e.waypoints||[]).slice(1,-1),target],d=curvePath(points),a=points[1],b=points.at(-2),attr=interactive?'data-ethernet="true"':'';
 const aa=Math.atan2(a.y-port.y,a.x-port.x)*180/Math.PI,ab=Math.atan2(b.y-target.y,b.x-target.x)*180/Math.PI;
 // Functional external computer symbol: position follows its Ethernet endpoint.
 const device=`<g ${interactive?'data-ethernet-device="true"':''} transform="translate(${target.x-82} ${target.y+22})"><rect width="164" height="64" rx="6" fill="#223340" stroke="#8296a5" stroke-width="2"/><rect x="8" y="7" width="148" height="49" rx="2" fill="#102a31"/><text x="82" y="30" text-anchor="middle" font-family="Arial" font-size="17" font-weight="bold" fill="#75efb9">TIA Portal</text><text x="82" y="46" text-anchor="middle" font-family="Arial" font-size="11" fill="#c1dde0">${escapeHtml(e.deviceLabel||'Programming PC')}</text><path d="M -11 68 H175 L162 77 H2 Z" fill="#607786" stroke="#223340"/><path d="M 82 0 V-22" stroke="#536d78" stroke-width="5"/></g>`;
 let mid=points[Math.floor(points.length/2)];if(points.length===2)mid={x:(port.x+target.x)/2,y:(port.y+target.y)/2};
 mid={x:Math.max(65,Math.min(1380,mid.x)),y:mid.y};
 return `<g ${attr} class="ethernet-cable"><title>Ethernet · TIA Portal / PROFINET · diagram only</title>${selected?`<path d="${d}" stroke="#ffcf49" stroke-opacity=".5" stroke-width="17" fill="none"/>`:''}<path d="${d}" fill="none" stroke="#111a21" stroke-opacity=".4" stroke-width="13" transform="translate(1 4)" filter="url(#leadShadow)"/><path d="${d}" fill="none" stroke="#14372a" stroke-width="10" stroke-linecap="round"/><path d="${d}" fill="none" stroke="${e.color}" stroke-width="7.5" stroke-linecap="round"/><path d="${d}" fill="none" stroke="white" stroke-opacity=".55" stroke-width="1.7" transform="translate(0 -1.5)"/>${interactive?`<path ${attr} d="${d}" fill="none" stroke="transparent" stroke-width="24" class="wire-hit"/>`:''}${device}${rj45Plug(port.x,port.y,aa,e.color,attr)}${rj45Plug(target.x,target.y,ab,e.color,interactive?'data-ethernet-device="true"':'')}${labels?`<g ${attr} transform="translate(${mid.x} ${mid.y})"><rect x="-59" y="-14" width="118" height="28" rx="5" fill="#fffef8" stroke="#315342"/><text y="5" text-anchor="middle" font-size="15" font-weight="bold" font-family="Arial" fill="#204c38">${escapeHtml(e.label||'ETH1')}</text></g>`:''}${editing&&!e.locked?points.slice(1,-1).map((p,i)=>`<circle data-ethernet-waypoint="${i+1}" cx="${p.x}" cy="${p.y}" r="8" fill="#ffecaa" stroke="#8f6500" stroke-width="2"/>`).join(''):''}</g>`;
}
