export const clone=x=>JSON.parse(JSON.stringify(x));
export function loadRecovery(){try{const p=JSON.parse(localStorage.getItem('sabronpro:recovery'));return p?.kitId==='sabronpro-s7-1200'?p:null}catch{return null}}
export function persist(p){try{localStorage.setItem('sabronpro:recovery',JSON.stringify(p));return true}catch{return false}}
export function saveNamed(p){const all=listProjects();const copy=clone(p);copy.savedAt=new Date().toISOString();all[p.projectId]=copy;localStorage.setItem('sabronpro:projects',JSON.stringify(all));persist(copy);return copy}
export function listProjects(){try{return JSON.parse(localStorage.getItem('sabronpro:projects'))||{}}catch{return {}}}
export function validateImport(p,kit){
 if(p?.kitId!=='sabronpro-s7-1200'||p.version!==1||!Array.isArray(p.wires)||p.wires.length>250||typeof p.title!=='string'||p.title.length>250)throw Error('This is not a supported SabronPro project.');
 if(p.ethernet){const e=p.ethernet;if(e.portId!=='TIA_PROFINET'||!/^#[0-9a-f]{6}$/i.test(e.color)||!e.endpoint||!Number.isFinite(e.endpoint.x)||!Number.isFinite(e.endpoint.y)||e.endpoint.x<85||e.endpoint.x>1360||e.endpoint.y<20||e.endpoint.y>1080||!Array.isArray(e.waypoints)||e.waypoints.length<2||e.waypoints.length>500||e.waypoints.some(v=>!Number.isFinite(v.x)||!Number.isFinite(v.y)))throw Error('Invalid Ethernet cable.');for(const key of ['label','deviceLabel','notes'])if(e[key]!==undefined&&typeof e[key]!=='string')throw Error('Invalid Ethernet label.');}
 const ids=new Set();for(const w of p.wires){if(typeof w.id!=='string'||w.id.length>80||!w.id||ids.has(w.id)||typeof w.from!=='string'||typeof w.to!=='string'||!/^#[0-9a-f]{6}$/i.test(w.color))throw Error('Invalid wire definition.');ids.add(w.id);if(!Array.isArray(w.waypoints)||w.waypoints.length<2||w.waypoints.length>500||w.waypoints.some(v=>!Number.isFinite(v.x)||!Number.isFinite(v.y)||Math.abs(v.x)>10000||Math.abs(v.y)>10000))throw Error('Invalid cable route.');for(const key of ['label','notes','function'])if(w[key]!==undefined&&typeof w[key]!=='string')throw Error('Invalid cable text.');}
 for(const v of Object.values(p.calibration||{})){if(!Number.isFinite(v.x)||!Number.isFinite(v.y)||v.x<0||v.x>1448||v.y<0||v.y>1086)throw Error('Invalid calibration coordinates.');for(const key of ['radius','w','h','maxPlugs'])if(v[key]!==undefined&&(!Number.isFinite(v[key])||v[key]<1||v[key]>2500))throw Error('Invalid calibration dimensions.');}
 for(const [id,v] of Object.entries(p.states||{}))if(!Number.isFinite(v)||v<0||v>100)throw Error(`Invalid control state: ${id}`);
 if(p.table){const t=p.table;for(const key of ['x','y','width','fontSize'])if(t[key]!==undefined&&(!Number.isFinite(t[key])||t[key]<0||t[key]>2500))throw Error('Invalid table settings.');if(t.columns&&(!Array.isArray(t.columns)||!t.columns.length||t.columns.some(c=>!['Wire','From','To','Color','Function','Notes'].includes(c))))throw Error('Invalid table columns.');}
 return p;
}
export function download(name,text,type='application/json'){const b=text instanceof Blob?text:new Blob([text],{type}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
